/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Connections.ConnectionToDB;
import Forms.Login;
import Students.AddStudents;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Black Code
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;
public class AdminPanel extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        conn = ConnectionToDB.ConnectToDB();
         this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

       //  displayBarChart();
    }
    public void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }

    public void displayBarChart(){
    try{
            String sql = "SELECT course , vote_count FROM courses";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(ConnectionToDB.ConnectToDB(),sql);
            JFreeChart chart = ChartFactory.createLineChart("Pie Chart Title","Course","Vote Count", dataset,PlotOrientation.VERTICAL ,false,true,true);
            BarRenderer render = null;
            CategoryPlot plot = null;
            render = new BarRenderer();
            
      
            ChartFrame frame = new ChartFrame("Query Chart",chart);
            frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            frame.setSize(1353, 697);
            frame.setResizable(false);
            frame.setVisible(true); 
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        addCourseItem = new javax.swing.JMenu();
        addCandidatesItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        addPartyItem = new javax.swing.JMenuItem();
        addPositionItem = new javax.swing.JMenuItem();
        addStudentItem = new javax.swing.JMenuItem();
        addUserItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        viewVotesItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        addCourseItem.setText("File");

        addCandidatesItem.setText("Add Candidates");
        addCandidatesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidatesItemActionPerformed(evt);
            }
        });
        addCourseItem.add(addCandidatesItem);

        jMenuItem1.setText("Add Course");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        addCourseItem.add(jMenuItem1);

        addPartyItem.setText("Add Party");
        addPartyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPartyItemActionPerformed(evt);
            }
        });
        addCourseItem.add(addPartyItem);

        addPositionItem.setText("Add Position");
        addPositionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPositionItemActionPerformed(evt);
            }
        });
        addCourseItem.add(addPositionItem);

        addStudentItem.setText("Add Student");
        addStudentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentItemActionPerformed(evt);
            }
        });
        addCourseItem.add(addStudentItem);

        addUserItem.setText("Add User");
        addUserItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserItemActionPerformed(evt);
            }
        });
        addCourseItem.add(addUserItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        addCourseItem.add(exitItem);

        jMenuBar1.add(addCourseItem);

        jMenu2.setText("Report");

        viewVotesItem.setText("View Votes");
        viewVotesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVotesItemActionPerformed(evt);
            }
        });
        jMenu2.add(viewVotesItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(794, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCandidatesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidatesItemActionPerformed
         AddCandidatesPanel acp = new AddCandidatesPanel();
         acp.setVisible(true);
    }//GEN-LAST:event_addCandidatesItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddCourse ac = new AddCourse();
        ac.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void addPartyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPartyItemActionPerformed
        AddParty ap = new AddParty();
        ap.setVisible(true);
    }//GEN-LAST:event_addPartyItemActionPerformed

    private void addPositionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPositionItemActionPerformed
        AddPositions ap = new AddPositions();
        ap.setVisible(true);
    }//GEN-LAST:event_addPositionItemActionPerformed

    private void addUserItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserItemActionPerformed
        AddUser au = new AddUser();
        au.setVisible(true);
    }//GEN-LAST:event_addUserItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        Login l = new Login();
        close();
        l.setVisible(true);
    }//GEN-LAST:event_exitItemActionPerformed

    private void addStudentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentItemActionPerformed
        AddStudents ad = new AddStudents();
        ad.setVisible(true);
    }//GEN-LAST:event_addStudentItemActionPerformed

    private void viewVotesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVotesItemActionPerformed
        ViewVotesPanel vvp = new ViewVotesPanel();
        close();
        vvp.setVisible(true);
    }//GEN-LAST:event_viewVotesItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              /*  if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                } */
                 UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCandidatesItem;
    private javax.swing.JMenu addCourseItem;
    private javax.swing.JMenuItem addPartyItem;
    private javax.swing.JMenuItem addPositionItem;
    private javax.swing.JMenuItem addStudentItem;
    private javax.swing.JMenuItem addUserItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem viewVotesItem;
    // End of variables declaration//GEN-END:variables
}
